# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\markveligod\Desktop\budget\widgets\Finder.ui',
# licensing of 'C:\Users\markveligod\Desktop\budget\widgets\Finder.ui' applies.
#
# Created: Sun Apr 21 20:47:21 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_FormFinder(object):
    def setupUi(self, FormFinder):
        FormFinder.setObjectName("FormFinder")
        FormFinder.resize(507, 590)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(FormFinder)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(FormFinder)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.grb_box = QtWidgets.QComboBox(self.groupBox)
        self.grb_box.setObjectName("grb_box")
        self.grb_box.addItem("")
        self.grb_box.setItemText(0, "")
        self.grb_box.addItem("")
        self.grb_box.addItem("")
        self.horizontalLayout_2.addWidget(self.grb_box)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(FormFinder)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(55, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.spisok_grb_box = QtWidgets.QComboBox(self.groupBox_2)
        self.spisok_grb_box.setObjectName("spisok_grb_box")
        self.spisok_grb_box.addItem("")
        self.spisok_grb_box.setItemText(0, "")
        self.spisok_grb_box.addItem("")
        self.spisok_grb_box.addItem("")
        self.horizontalLayout_4.addWidget(self.spisok_grb_box)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(FormFinder)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(55, -1, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.spisok_sub_box = QtWidgets.QComboBox(self.groupBox_3)
        self.spisok_sub_box.setObjectName("spisok_sub_box")
        self.spisok_sub_box.addItem("")
        self.spisok_sub_box.setItemText(0, "")
        self.spisok_sub_box.addItem("")
        self.spisok_sub_box.addItem("")
        self.horizontalLayout_6.addWidget(self.spisok_sub_box)
        self.horizontalLayout_6.setStretch(1, 1)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.listWidget = QtWidgets.QListWidget(FormFinder)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_3.addWidget(self.listWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.find_btn = QtWidgets.QPushButton(FormFinder)
        self.find_btn.setObjectName("find_btn")
        self.horizontalLayout.addWidget(self.find_btn)
        self.close_btn = QtWidgets.QPushButton(FormFinder)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(FormFinder)
        QtCore.QMetaObject.connectSlotsByName(FormFinder)

    def retranslateUi(self, FormFinder):
        FormFinder.setWindowTitle(QtWidgets.QApplication.translate("FormFinder", "Blockchain Федерального бюджета", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("FormFinder", "поиск данных", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("FormFinder", "категория поиска", None, -1))
        self.grb_box.setItemText(1, QtWidgets.QApplication.translate("FormFinder", "Главный распорядитель бюджета", None, -1))
        self.grb_box.setItemText(2, QtWidgets.QApplication.translate("FormFinder", "Раздел", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("FormFinder", "Главный распорядитель бюджета", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("FormFinder", "Список", None, -1))
        self.spisok_grb_box.setItemText(1, QtWidgets.QApplication.translate("FormFinder", "Федеральное агентство научных организаций", None, -1))
        self.spisok_grb_box.setItemText(2, QtWidgets.QApplication.translate("FormFinder", "Министерство промышленности и торговли Российской Федерации", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("FormFinder", "Раздел", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("FormFinder", "Список", None, -1))
        self.spisok_sub_box.setItemText(1, QtWidgets.QApplication.translate("FormFinder", "Общегосударственные вопросы", None, -1))
        self.spisok_sub_box.setItemText(2, QtWidgets.QApplication.translate("FormFinder", "Национальная экономика", None, -1))
        self.find_btn.setText(QtWidgets.QApplication.translate("FormFinder", "поиск", None, -1))
        self.close_btn.setText(QtWidgets.QApplication.translate("FormFinder", "закрыть", None, -1))

