# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\markveligod\Desktop\budget\widgets\Structure.ui',
# licensing of 'C:\Users\markveligod\Desktop\budget\widgets\Structure.ui' applies.
#
# Created: Sat Apr 20 07:21:37 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_FormStructure(object):
    def setupUi(self, FormStructure):
        FormStructure.setObjectName("FormStructure")
        FormStructure.resize(740, 344)
        self.groupBox_10 = QtWidgets.QGroupBox(FormStructure)
        self.groupBox_10.setGeometry(QtCore.QRect(9, 9, 721, 326))
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.grbs_box = QtWidgets.QComboBox(self.groupBox_5)
        self.grbs_box.setObjectName("grbs_box")
        self.grbs_box.addItem("")
        self.grbs_box.setItemText(0, "")
        self.grbs_box.addItem("")
        self.grbs_box.addItem("")
        self.horizontalLayout_5.addWidget(self.grbs_box)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.section_box = QtWidgets.QComboBox(self.groupBox_6)
        self.section_box.setObjectName("section_box")
        self.section_box.addItem("")
        self.section_box.setItemText(0, "")
        self.section_box.addItem("")
        self.section_box.addItem("")
        self.horizontalLayout_6.addWidget(self.section_box)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sub_box_1 = QtWidgets.QComboBox(self.groupBox)
        self.sub_box_1.setObjectName("sub_box_1")
        self.sub_box_1.addItem("")
        self.sub_box_1.setItemText(0, "")
        self.sub_box_1.addItem("")
        self.sub_box_1.addItem("")
        self.sub_box_1.addItem("")
        self.sub_box_1.addItem("")
        self.sub_box_1.addItem("")
        self.sub_box_1.addItem("")
        self.sub_box_1.addItem("")
        self.sub_box_1.addItem("")
        self.sub_box_1.addItem("")
        self.sub_box_1.addItem("")
        self.sub_box_1.addItem("")
        self.sub_box_1.addItem("")
        self.sub_box_1.addItem("")
        self.horizontalLayout.addWidget(self.sub_box_1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sub_box_4 = QtWidgets.QComboBox(self.groupBox_2)
        self.sub_box_4.setObjectName("sub_box_4")
        self.sub_box_4.addItem("")
        self.sub_box_4.setItemText(0, "")
        self.sub_box_4.addItem("")
        self.sub_box_4.addItem("")
        self.sub_box_4.addItem("")
        self.sub_box_4.addItem("")
        self.sub_box_4.addItem("")
        self.sub_box_4.addItem("")
        self.sub_box_4.addItem("")
        self.sub_box_4.addItem("")
        self.sub_box_4.addItem("")
        self.sub_box_4.addItem("")
        self.sub_box_4.addItem("")
        self.sub_box_4.addItem("")
        self.horizontalLayout_2.addWidget(self.sub_box_4)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.prog_box = QtWidgets.QComboBox(self.groupBox_3)
        self.prog_box.setObjectName("prog_box")
        self.prog_box.addItem("")
        self.prog_box.setItemText(0, "")
        self.prog_box.addItem("")
        self.prog_box.addItem("")
        self.prog_box.addItem("")
        self.prog_box.addItem("")
        self.prog_box.addItem("")
        self.prog_box.addItem("")
        self.prog_box.addItem("")
        self.prog_box.addItem("")
        self.prog_box.addItem("")
        self.prog_box.addItem("")
        self.prog_box.addItem("")
        self.prog_box.addItem("")
        self.prog_box.addItem("")
        self.horizontalLayout_3.addWidget(self.prog_box)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_11.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pod_box = QtWidgets.QComboBox(self.groupBox_4)
        self.pod_box.setObjectName("pod_box")
        self.pod_box.addItem("")
        self.pod_box.setItemText(0, "")
        self.pod_box.addItem("")
        self.pod_box.addItem("")
        self.pod_box.addItem("")
        self.pod_box.addItem("")
        self.pod_box.addItem("")
        self.pod_box.addItem("")
        self.pod_box.addItem("")
        self.pod_box.addItem("")
        self.pod_box.addItem("")
        self.pod_box.addItem("")
        self.horizontalLayout_4.addWidget(self.pod_box)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.event_box = QtWidgets.QComboBox(self.groupBox_7)
        self.event_box.setObjectName("event_box")
        self.event_box.addItem("")
        self.event_box.setItemText(0, "")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.event_box.addItem("")
        self.horizontalLayout_7.addWidget(self.event_box)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.view_box = QtWidgets.QComboBox(self.groupBox_8)
        self.view_box.setObjectName("view_box")
        self.view_box.addItem("")
        self.view_box.setItemText(0, "")
        self.view_box.addItem("")
        self.view_box.addItem("")
        self.view_box.addItem("")
        self.view_box.addItem("")
        self.view_box.addItem("")
        self.view_box.addItem("")
        self.view_box.addItem("")
        self.view_box.addItem("")
        self.view_box.addItem("")
        self.view_box.addItem("")
        self.view_box.addItem("")
        self.horizontalLayout_8.addWidget(self.view_box)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.line_sum = QtWidgets.QLineEdit(self.groupBox_9)
        self.line_sum.setObjectName("line_sum")
        self.horizontalLayout_9.addWidget(self.line_sum)
        self.verticalLayout.addWidget(self.groupBox_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.send_btn = QtWidgets.QPushButton(self.groupBox_10)
        self.send_btn.setObjectName("send_btn")
        self.horizontalLayout_10.addWidget(self.send_btn)
        self.close_btn = QtWidgets.QPushButton(self.groupBox_10)
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout_10.addWidget(self.close_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)

        self.retranslateUi(FormStructure)
        QtCore.QMetaObject.connectSlotsByName(FormStructure)
        FormStructure.setTabOrder(self.grbs_box, self.section_box)
        FormStructure.setTabOrder(self.section_box, self.sub_box_1)
        FormStructure.setTabOrder(self.sub_box_1, self.sub_box_4)
        FormStructure.setTabOrder(self.sub_box_4, self.prog_box)
        FormStructure.setTabOrder(self.prog_box, self.pod_box)
        FormStructure.setTabOrder(self.pod_box, self.event_box)
        FormStructure.setTabOrder(self.event_box, self.view_box)
        FormStructure.setTabOrder(self.view_box, self.line_sum)
        FormStructure.setTabOrder(self.line_sum, self.send_btn)
        FormStructure.setTabOrder(self.send_btn, self.close_btn)

    def retranslateUi(self, FormStructure):
        FormStructure.setWindowTitle(QtWidgets.QApplication.translate("FormStructure", "Form", None, -1))
        self.groupBox_10.setTitle(QtWidgets.QApplication.translate("FormStructure", "Ведомственная структура расходов", None, -1))
        self.groupBox_5.setTitle(QtWidgets.QApplication.translate("FormStructure", "Главный распорядитель бюджетный средств", None, -1))
        self.grbs_box.setItemText(1, QtWidgets.QApplication.translate("FormStructure", "Федеральное агентство научных организаций", None, -1))
        self.grbs_box.setItemText(2, QtWidgets.QApplication.translate("FormStructure", "Министерство промышленности и торговли Российской Федерации", None, -1))
        self.groupBox_6.setTitle(QtWidgets.QApplication.translate("FormStructure", "Раздел", None, -1))
        self.section_box.setItemText(1, QtWidgets.QApplication.translate("FormStructure", "Общегосударственные вопросы", None, -1))
        self.section_box.setItemText(2, QtWidgets.QApplication.translate("FormStructure", "Национальная экономика", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("FormStructure", "Подраздел", None, -1))
        self.sub_box_1.setItemText(1, QtWidgets.QApplication.translate("FormStructure", "Функционирование Президента Российской Федерации", None, -1))
        self.sub_box_1.setItemText(2, QtWidgets.QApplication.translate("FormStructure", "Функционирование высшего должностного лица субъекта Российской Федерации и муниципального образования", None, -1))
        self.sub_box_1.setItemText(3, QtWidgets.QApplication.translate("FormStructure", "Функционирование законодательных (представительных) органов государственной власти и представительных органов муниципальных образований", None, -1))
        self.sub_box_1.setItemText(4, QtWidgets.QApplication.translate("FormStructure", "Функционирование Правительства Российской Федерации, высших исполнительных органов государственной власти субъектов Российской Федерации, местных администраций", None, -1))
        self.sub_box_1.setItemText(5, QtWidgets.QApplication.translate("FormStructure", "Судебная система", None, -1))
        self.sub_box_1.setItemText(6, QtWidgets.QApplication.translate("FormStructure", "Обеспечение деятельности финансовых, налоговых и таможенных органов и органов финансового (финансово-бюджетного) надзора", None, -1))
        self.sub_box_1.setItemText(7, QtWidgets.QApplication.translate("FormStructure", "Обеспечение проведения выборов и референдумов", None, -1))
        self.sub_box_1.setItemText(8, QtWidgets.QApplication.translate("FormStructure", "Международные отношения и международное сотрудничество", None, -1))
        self.sub_box_1.setItemText(9, QtWidgets.QApplication.translate("FormStructure", "Государственный материальный резерв", None, -1))
        self.sub_box_1.setItemText(10, QtWidgets.QApplication.translate("FormStructure", "Фундаментальные исследования", None, -1))
        self.sub_box_1.setItemText(11, QtWidgets.QApplication.translate("FormStructure", "Резервные фонды", None, -1))
        self.sub_box_1.setItemText(12, QtWidgets.QApplication.translate("FormStructure", "Прикладные научные исследования в области общегосударственных вопросов", None, -1))
        self.sub_box_1.setItemText(13, QtWidgets.QApplication.translate("FormStructure", "Другие общегосударственные вопросы", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("FormStructure", "Подраздел", None, -1))
        self.sub_box_4.setItemText(1, QtWidgets.QApplication.translate("FormStructure", "Общеэкономические вопросы", None, -1))
        self.sub_box_4.setItemText(2, QtWidgets.QApplication.translate("FormStructure", "Топливно-энергетический комплекс", None, -1))
        self.sub_box_4.setItemText(3, QtWidgets.QApplication.translate("FormStructure", "Исследование и использование космического пространства", None, -1))
        self.sub_box_4.setItemText(4, QtWidgets.QApplication.translate("FormStructure", "Воспроизводство минерально-сырьевой базы", None, -1))
        self.sub_box_4.setItemText(5, QtWidgets.QApplication.translate("FormStructure", "Сельское хозяйство и рыболовство", None, -1))
        self.sub_box_4.setItemText(6, QtWidgets.QApplication.translate("FormStructure", "Водное хозяйство", None, -1))
        self.sub_box_4.setItemText(7, QtWidgets.QApplication.translate("FormStructure", "Лесное хозяйство", None, -1))
        self.sub_box_4.setItemText(8, QtWidgets.QApplication.translate("FormStructure", "Транспорт", None, -1))
        self.sub_box_4.setItemText(9, QtWidgets.QApplication.translate("FormStructure", "Дорожное хозяйство (дорожные фонды)", None, -1))
        self.sub_box_4.setItemText(10, QtWidgets.QApplication.translate("FormStructure", "Связь и информатика", None, -1))
        self.sub_box_4.setItemText(11, QtWidgets.QApplication.translate("FormStructure", "Прикладные научные исследования в области национальной экономики", None, -1))
        self.sub_box_4.setItemText(12, QtWidgets.QApplication.translate("FormStructure", "Другие вопросы в области национальной экономики", None, -1))
        self.groupBox_3.setTitle(QtWidgets.QApplication.translate("FormStructure", "Программа", None, -1))
        self.prog_box.setItemText(1, QtWidgets.QApplication.translate("FormStructure", "Государственная программа Российской Федерации \"Развитие здравоохранения\"", None, -1))
        self.prog_box.setItemText(2, QtWidgets.QApplication.translate("FormStructure", "Государственная программа Российской Федерации \"Развитие культуры и туризма\" на 2013 - 2020 годы", None, -1))
        self.prog_box.setItemText(3, QtWidgets.QApplication.translate("FormStructure", "Государственная программа Российской Федерации \"Развитие науки и технологий\" на 2013 - 2020 годы", None, -1))
        self.prog_box.setItemText(4, QtWidgets.QApplication.translate("FormStructure", "Реализация функций иных федеральных органов государственной власти", None, -1))
        self.prog_box.setItemText(5, QtWidgets.QApplication.translate("FormStructure", "Государственная программа развития сельского хозяйства и регулирования рынков сельскохозяйственной продукции, сырья и продовольствия на 2013 - 2020 годы", None, -1))
        self.prog_box.setItemText(6, QtWidgets.QApplication.translate("FormStructure", "Государственная программа Российской Федерации \"Охрана окружающей среды\" на 2012 - 2020 годы", None, -1))
        self.prog_box.setItemText(7, QtWidgets.QApplication.translate("FormStructure", "Государственная программа Российской Федерации \"Развитие авиационной промышленности на 2013 - 2025 годы\"", None, -1))
        self.prog_box.setItemText(8, QtWidgets.QApplication.translate("FormStructure", "Государственная программа Российской Федерации \"Развитие внешнеэкономической деятельности\"", None, -1))
        self.prog_box.setItemText(9, QtWidgets.QApplication.translate("FormStructure", "Государственная программа Российской Федерации \"Развитие промышленности и повышение ее конкурентоспособности\"", None, -1))
        self.prog_box.setItemText(10, QtWidgets.QApplication.translate("FormStructure", "Государственная программа Российской Федерации \"Обеспечение общественного порядка и противодействие преступности\"", None, -1))
        self.prog_box.setItemText(11, QtWidgets.QApplication.translate("FormStructure", "Государственная программа Российской Федерации \"Развитие судостроения и техники для освоения шельфовых месторождений на 2013 - 2030 годы\"", None, -1))
        self.prog_box.setItemText(12, QtWidgets.QApplication.translate("FormStructure", "Государственная программа Российской Федерации \"Развитие электронной и радиоэлектронной промышленности на 2013 - 2025 годы\"", None, -1))
        self.prog_box.setItemText(13, QtWidgets.QApplication.translate("FormStructure", "Государственная программа Российской Федерации \"Развитие фармацевтической и медицинской промышленности\" на 2013 - 2020 годы", None, -1))
        self.groupBox_4.setTitle(QtWidgets.QApplication.translate("FormStructure", "Подпрограмма", None, -1))
        self.pod_box.setItemText(1, QtWidgets.QApplication.translate("FormStructure", "Подпрограмма \"Авиационная наука и технологии\"", None, -1))
        self.pod_box.setItemText(2, QtWidgets.QApplication.translate("FormStructure", "Подпрограмма \"Создание национальной системы поддержки развития внешнеэкономической деятельности\"", None, -1))
        self.pod_box.setItemText(3, QtWidgets.QApplication.translate("FormStructure", "Подпрограмма \"Развитие и внедрение инновационных методов диагностики, профилактики и лечения, а также основ персонализированной медицины\"", None, -1))
        self.pod_box.setItemText(4, QtWidgets.QApplication.translate("FormStructure", "Подпрограмма \"Наследие\"", None, -1))
        self.pod_box.setItemText(5, QtWidgets.QApplication.translate("FormStructure", "Подпрограмма \"Фундаментальные научные исследования\"", None, -1))
        self.pod_box.setItemText(6, QtWidgets.QApplication.translate("FormStructure", "Подпрограмма \"Научно-техническое обеспечение развития отраслей агропромышленного комплекса\"", None, -1))
        self.pod_box.setItemText(7, QtWidgets.QApplication.translate("FormStructure", "Подпрограмма \"Развитие системы технического регулирования, стандартизации и обеспечение единства измерений\"", None, -1))
        self.pod_box.setItemText(8, QtWidgets.QApplication.translate("FormStructure", "Подпрограмма \"Содействие проведению научных исследований и опытных разработок в гражданских отраслях промышленности\"", None, -1))
        self.pod_box.setItemText(9, QtWidgets.QApplication.translate("FormStructure", "Подпрограмма \"Самолетостроение\"", None, -1))
        self.pod_box.setItemText(10, QtWidgets.QApplication.translate("FormStructure", "Иные непрограммные мероприятия", None, -1))
        self.groupBox_7.setTitle(QtWidgets.QApplication.translate("FormStructure", "Мероприятие", None, -1))
        self.event_box.setItemText(1, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Развитие фундаментальной, трансляционной и персонализированной медицины\"", None, -1))
        self.event_box.setItemText(2, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Развитие музейного дела\"", None, -1))
        self.event_box.setItemText(3, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Выполнение фундаментальных научных исследований учреждениями государственных академий наук, финансовое обеспечение государственных академий наук\"", None, -1))
        self.event_box.setItemText(4, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Выполнение фундаментальных научных исследований по приоритетным направлениям, определяемым Российской академией наук\"", None, -1))
        self.event_box.setItemText(5, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Обеспечение сохранения коллекции генетических ресурсов растений\"", None, -1))
        self.event_box.setItemText(6, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Реализация Федеральной научно-технической программы развития сельского хозяйства\"", None, -1))
        self.event_box.setItemText(7, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Выполнение научно-исследовательских работ в целях развития науки и технологий в авиастроении и технологической и инженерной инфраструктуры, в том числе на базе инновационных территориальных кластеров\"", None, -1))
        self.event_box.setItemText(8, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Промоутерская поддержка экспорта и инвестиционного сотрудничества\"", None, -1))
        self.event_box.setItemText(9, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Развитие системы технического регулирования и стандартизации\"", None, -1))
        self.event_box.setItemText(10, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Научные исследования и сопровождение приоритетных и инновационных проектов\"", None, -1))
        self.event_box.setItemText(11, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Государственная поддержка российских организаций самолетостроения\"", None, -1))
        self.event_box.setItemText(12, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Выполнение научно-исследовательских и опытно-конструкторских работ в области самолетостроения\"", None, -1))
        self.event_box.setItemText(13, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Выполнение научно-исследовательских и опытно-конструкторских работ в области вертолетостроения\"", None, -1))
        self.event_box.setItemText(14, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Выполнение научно-исследовательских и опытно-конструкторских работ в области авиационного двигателестроения\"", None, -1))
        self.event_box.setItemText(15, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Государственная поддержка российских научных организаций, осуществляющих исследования в области развития авиации и авиационной деятельности\"", None, -1))
        self.event_box.setItemText(16, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Научно-аналитическое обеспечение реализации государственной программы\"", None, -1))
        self.event_box.setItemText(17, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Создание научно-технического задела для развития морской и речной техники гражданского назначения\"", None, -1))
        self.event_box.setItemText(18, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Разработка новых технологий и создание инновационных проектов для производства гражданской морской и речной техники\"", None, -1))
        self.event_box.setItemText(19, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Государственная поддержка создания научно-технического задела\"", None, -1))
        self.event_box.setItemText(20, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Реализация иных проектов в области фармацевтической промышленности\"", None, -1))
        self.event_box.setItemText(21, QtWidgets.QApplication.translate("FormStructure", "Основное мероприятие \"Реализация иных проектов в области медицинской промышленности\"", None, -1))
        self.groupBox_8.setTitle(QtWidgets.QApplication.translate("FormStructure", "Вид расходов", None, -1))
        self.view_box.setItemText(1, QtWidgets.QApplication.translate("FormStructure", "Субсидии российским организациям на компенсацию части затрат на реализацию проектов по организации и проведению клинических испытаний имплантируемых медицинских изделий (Иные бюджетные ассигнования)", None, -1))
        self.view_box.setItemText(2, QtWidgets.QApplication.translate("FormStructure", "Финансовое обеспечение выполнения функций федеральных государственных органов, оказания услуг и выполнения работ (Предоставление субсидий бюджетным, автономным учреждениям и иным некоммерческим организациям)", None, -1))
        self.view_box.setItemText(3, QtWidgets.QApplication.translate("FormStructure", "Субсидии российским организациям на возмещение части затрат на реализацию проектов по организации и проведению клинических исследований лекарственных препаратов (Иные бюджетные ассигнования)", None, -1))
        self.view_box.setItemText(4, QtWidgets.QApplication.translate("FormStructure", "Субсидии российским организациям на возмещение части затрат на реализацию проектов по разработке схожих по фармакотерапевтическому действию и улучшенных аналогов инновационных лекарственных препаратов (Иные бюджетные ассигнования)", None, -1))
        self.view_box.setItemText(5, QtWidgets.QApplication.translate("FormStructure", "Субсидии российским организациям на финансовое обеспечение части затрат на создание научно-технического задела по разработке базовых технологий производства приоритетных электронных компонентов и радиоэлектронной аппаратуры (Иные бюджетные ассигнования)", None, -1))
        self.view_box.setItemText(6, QtWidgets.QApplication.translate("FormStructure", "Финансовое обеспечение выполнения функций федеральных государственных органов, оказания услуг и выполнения работ (Закупка товаров, работ и услуг для обеспечения государственных (муниципальных) нужд)", None, -1))
        self.view_box.setItemText(7, QtWidgets.QApplication.translate("FormStructure", "Взнос в уставный капитал публичного акционерного общества \"Объединенная авиастроительная корпорация\", г. Москва, в том числе для осуществления последующих взносов в уставные капиталы дочерних обществ, на финансовое обеспечение затрат в рамках реализации проекта по созданию широкофюзеляжного дальнемагистрального самолета (Капитальные вложения в объекты государственной (муниципальной) собственности)", None, -1))
        self.view_box.setItemText(8, QtWidgets.QApplication.translate("FormStructure", "Финансовое обеспечение выполнения функций федеральных государственных органов, оказания услуг и выполнения работ (Иные бюджетные ассигнования)", None, -1))
        self.view_box.setItemText(9, QtWidgets.QApplication.translate("FormStructure", "Финансовое обеспечение выполнения функций федеральных государственных органов, оказания услуг и выполнения работ (Расходы на выплаты персоналу в целях обеспечения выполнения функций государственными (муниципальными) органами, казенными учреждениями, органами управления государственными внебюджетными фондами)", None, -1))
        self.view_box.setItemText(10, QtWidgets.QApplication.translate("FormStructure", "Финансовое обеспечение выполнения функций федеральных государственных органов, оказания услуг и выполнения работ (Капитальные вложения в объекты государственной (муниципальной) собственности)", None, -1))
        self.view_box.setItemText(11, QtWidgets.QApplication.translate("FormStructure", "Финансовое обеспечение выполнения функций федеральных государственных органов, оказания услуг и выполнения работ (Социальное обеспечение и иные выплаты населению)", None, -1))
        self.groupBox_9.setTitle(QtWidgets.QApplication.translate("FormStructure", "Сумма бюджетных средств", None, -1))
        self.send_btn.setText(QtWidgets.QApplication.translate("FormStructure", "Отправить", None, -1))
        self.close_btn.setText(QtWidgets.QApplication.translate("FormStructure", "Закрыть", None, -1))

